# aws region - relevant for aws related components (sqs,ecs)
aws_default_region: us-east-1

# Database url - relevant for database oriented state managers
database_url: postgresql://flotilla:flotilla@localhost/flotilla?sslmode=disable

#
# Configure which managers and clients to use
#
state_manager: postgres
queue_manager: sqs
cluster_client: ecs
logs_client: cloudwatch
execution_engine: ecs
enabled_workers:
  - retry
  - submit
  - status


# Log namespace
log:
  namespace: flotilla-os-logs
  retention_days: 90
  driver:
    name: awslogs
    options:
      awslogs-group: flotilla-os-logs
      awslogs-stream-prefix: flotilla
      awslogs-region: us-east-1

# Queue namespace
queue:
  namespace: dev-flotilla
  # 7 day retention
  retention_seconds: 604800
  # 45 seconds allowed processing time before re-queueing
  process_time: 45
  # main status update queue name
  status: flotilla-status-updates-dev

worker:
  retry_interval_seconds: 30
  submit_interval_seconds: 30
  status_interval_seconds: 5
  reassign_interval_seconds: 30

http:
  server:
    read_timeout_seconds: 5
    write_timeout_seconds: 10
    listen_address: :3000
    cors_allowed_origins:
     - http://localhost:3000

#
# Environment variable name to inject into every run
# with ownership information set - "who -owns- this run?"
#
owner_id_var: FLOTILLA_RUN_OWNER_ID